# GitHub reference:
# https://docs.github.com/code-security/dependabot/working-with-dependabot/dependabot-options-reference
version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      aws-sdk:
        patterns: ["boto3", "botocore", "s3transfer"]
      python-quality:
        dependency-type: development
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directories: ["/proxy", "/emr", "/glue"]
    schedule:
      interval: weekly

