import {Alert, AppShell, Badge, Button, EmptyState, LoadingState, Panel, PanelHeader, Table, TableBody, TableCell, TableFrame, TableHead, TableHeaderCell, TableRow, Tabs, useBrowserRoute, usePollingResource} from "@mystack/ui";
import {useCallback, useEffect, useState} from "react";
import {GlueUiApi} from "./api";
import {formatGlueRoute, parseGlueRoute, type GlueTab} from "./routes";
import type {GlueDatabase, GluePage, GluePartition, GlueTable} from "./types";
const api = new GlueUiApi();

export default function App() {
  const {route, navigate} = useBrowserRoute("/_mystack/ui/glue", parseGlueRoute, formatGlueRoute);
  const document = usePollingResource(useCallback(() => api.document(), []), 30_000);
  const databases = usePollingResource(useCallback(() => api.databases(), []), 30_000);
  const tables = usePollingResource(useCallback(() => route.databaseName ? api.tables(route.databaseName) : Promise.resolve(emptyPage<GlueTable>()), [route.databaseName]), 30_000);
  const detail = usePollingResource(useCallback(() => route.databaseName && route.tableName ? api.table(route.databaseName, route.tableName) : Promise.resolve(null), [route.databaseName, route.tableName]), 30_000);
  const status = databases.error || tables.error || detail.error ? "Attention required" : "Ready";
  return <AppShell service="AWS Glue Data Catalog" homeHref="/_mystack/ui/glue/" title="Data Catalog" description="Bounded SQLite-backed catalog exploration." status={status} navigation={<><a className="rounded-control px-3 py-1.5 text-sm text-code-ink/75 hover:bg-white/10 hover:text-white" href="/_mystack/ui/emr/">EMR</a><a aria-current="page" className="rounded-control bg-white/12 px-3 py-1.5 text-sm font-bold text-white" href="/_mystack/ui/glue/">Glue</a></>} actions={<Button onClick={() => { void databases.refresh(); void tables.refresh(); void detail.refresh(); }}>Refresh</Button>}>
    {document.data?.emulator.notice && <p className="text-sm text-ink-muted">{document.data.emulator.notice}</p>}
    {(databases.error || tables.error || detail.error) && <Alert>{String(databases.error || tables.error || detail.error)}</Alert>}
    <div className="mt-5 grid gap-5 xl:grid-cols-[18rem_18rem_minmax(0,1fr)]">
      <PageList title="Databases" page={databases.data ?? undefined} label="Database" selected={route.databaseName} onSelect={name => navigate({databaseName: name, tableName: null, tab: "schema"})} />
      <PageList title="Tables" page={tables.data ?? undefined} label="Table" selected={route.tableName} onSelect={name => navigate({databaseName: route.databaseName, tableName: name, tab: "schema"})} />
      <Panel>{detail.busy ? <LoadingState label="Loading table" /> : detail.data && route.databaseName ? <Detail database={route.databaseName} table={detail.data.resource} partitionCount={detail.data.partition_count} tab={route.tab} onTab={tab => navigate({databaseName: route.databaseName, tableName: detail.data!.resource.name, tab})} /> : <EmptyState title="Explore the Data Catalog" description="Select a database and table. Each panel requests only its own bounded page." />}</Panel>
    </div>
  </AppShell>;
}
function emptyPage<T>(): GluePage<T> { return {items: [], next_cursor: null, total_count: 0, diagnostics: {query_category: "none", query_strategy: "none", returned_count: 0}}; }
function PageList({title, page, label, selected, onSelect}: {title: string; page: GluePage<GlueDatabase | GlueTable | GluePartition> | undefined; label: string; selected: string | null; onSelect: (name: string) => void}) { return <Panel><PanelHeader eyebrow="Catalog" title={title} actions={<Badge>{page?.total_count ?? "—"}</Badge>} /><div className="p-3 grid gap-2">{!page ? <LoadingState label={`Loading ${title}`} /> : page.items.map(value => <button key={value.id} type="button" aria-label={`${label} ${"name" in value ? value.name : value.id}`} aria-current={selected === ("name" in value ? value.name : value.id) ? "true" : undefined} className="rounded-control border border-border p-3 text-left" onClick={() => onSelect("name" in value ? value.name : value.id)}><strong>{"name" in value ? value.name : value.id}</strong></button>)}</div></Panel>; }
function Detail({database, table, partitionCount, tab, onTab}: {database: string; table: GlueTable; partitionCount: number; tab: GlueTab; onTab: (tab: GlueTab) => void}) { return <><PanelHeader eyebrow={database} title={table.name} actions={<Badge>{table.table_type || "TABLE"}</Badge>} /><Tabs label="Table detail views" active={tab} onChange={value => onTab(value as GlueTab)} tabs={[{id:"schema",label:"Schema",panel:<Schema table={table} count={partitionCount}/>},{id:"partitions",label:"Partitions",panel:<Partitions database={database} table={table}/>},{id:"diagnostics",label:"Diagnostics",panel:<Diagnostics/>}]} /></>; }
function Schema({table, count}: {table: GlueTable; count: number}) { return <div className="p-4"><p id="partitionKeyList">Partitions: {count} · {table.partition_keys.map(key => key.Name).join(", ") || "none"}</p><TableFrame><Table><TableHead><TableRow><TableHeaderCell>Name</TableHeaderCell><TableHeaderCell>Type</TableHeaderCell></TableRow></TableHead><TableBody id="columnRows">{table.columns.map(column => <TableRow key={column.Name}><TableCell>{column.Name}</TableCell><TableCell>{column.Type}</TableCell></TableRow>)}</TableBody></Table></TableFrame></div>; }
function Partitions({database, table}: {database: string; table: GlueTable}) { const page = usePollingResource(useCallback(() => api.partitions(database, table.name), [database, table.name]), 30_000); return <div className="p-4">{!page.data ? <LoadingState label="Loading partitions" /> : <><p className="mb-3">{page.data.total_count} partitions · {page.data.diagnostics.query_strategy}</p><TableFrame><Table><TableBody id="partitionRows">{page.data.items.map(value => <TableRow key={value.id}><TableCell>{value.values.join(" / ")}</TableCell><TableCell>{value.definition.StorageDescriptor?.Location || "—"}</TableCell></TableRow>)}</TableBody></Table></TableFrame></>}</div>; }
function Diagnostics() { const [kind, setKind] = useState<"threads" | "tasks">("threads"); const [value, setValue] = useState<unknown>(null); useEffect(() => { void api.diagnostics(kind).then(setValue); }, [kind]); return <div className="p-4"><Button onClick={() => setKind("threads")}>Thread stacks</Button> <Button onClick={() => setKind("tasks")}>Asyncio tasks</Button><pre id={kind} className="mt-3 overflow-auto text-xs">{value ? JSON.stringify(value, null, 2) : "Loading diagnostics"}</pre></div>; }
